site_name: Documentation - ProfilePress WordPress Plugin
site_url: https://docs.profilepress.net/en/latest
site_description: Documentation for ProfilePress plugin - The ultimate plugin for creating user account forms such as login, registration, password reset, front-end edit profile forms as well as front-end user profile for WordPress
theme:
    name: readthedocs
google_analytics: ['UA-62480573-1', 'docs.profilepress.net']
repo_url: https://github.com/ProfilePress/documentation/
repo_name: GitHub
site_author: Collins Agbonghama
pages:
- Home: index.md
